services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    volumes:
      - ./:/myfolder/
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker
  database:
    platform: linux/arm64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "mydocker"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
  # database:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.mongo
  #   ports:
  #     - 27017:27017